version: "3"

services:
  app:
    image: {{project_name}}:latest
    container_name: {{project_name}}_app
    command:
      - "app"
    ports:
      - "9741:9741"
    env_file:
      - '../.env'
    volumes:
      - ../:/code
      - ../{{project_name}}_data:/data/
  {{project_name}}_highprio_workers:
    image: {{project_name}}:latest
    container_name: {{project_name}}_highprio_workers
    command:
      -  workers
      -  high_priority
    env_file:
      - '../.env'
    volumes:
      - ../:/code
      - ../{{project_name}}_data:/data/
  {{project_name}}_medprio_workers:
    image: {{project_name}}:latest
    container_name: {{project_name}}_medprio_workers
    command:
      -  workers
      -  medium_priority
    env_file:
      - '../.env'
    volumes:
      - ../:/code
      - ../{{project_name}}_exchange_data:/data/
  {{project_name}}_lowprio_workers:
    image: {{project_name}}:latest
    container_name: {{project_name}}_lowprio_workers
    command:
      -  workers
      -  low_priority
    env_file:
      - '../.env'
    volumes:
      - ../:/code
      - ../{{project_name}}_exchange_data:/data/
