version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: {{project_name}}_db
    env_file:
      - '../.env'
  redis:
    image: redis:latest
    container_name: {{project_name}}_redis
    env_file:
      - '../.env'
