services:
  postgres:
    image: postgres:latest
    container_name: {{cookiecutter.project_name}}_db
    volumes:
      - {{cookiecutter.project_name}}_db-data:/var/lib/postgresql/data
    env_file:
      - '../.env'
  redis:
    image: redis:latest
    container_name: {{cookiecutter.project_name}}_redis
    env_file:
      - '../.env'

volumes:
  {{cookiecutter.project_name}}_db-data: